---
name: 'Perl static checks'

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  perl-lint-checks:
    runs-on: ubuntu-latest
    name: "Perltidy"
    container:
      image: registry.opensuse.org/home/josegomezr/devel/openqa/ci/containers-tw/latest
      options: --user "1000:100"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cpanm --installdeps . --with-develop --notest
      - name: Run Tidyall
        run: GITHUB_ACTIONS=1 ./tools/tidyall --check-only --all --quiet

  perl-critic-checks:
    runs-on: ubuntu-latest
    name: "Perlcritic"
    container:
      image: registry.opensuse.org/home/josegomezr/devel/openqa/ci/containers-tw/latest
      options: --user "1000:100"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cpanm --installdeps . --with-develop --notest
      - name: Run Perlcritic
        run: ./tools/perlcritic --quiet .
