name: Check dlp

on:
  push:
    branches: [action-check-dlp]

jobs:
  dlp:
    env:
      IMAGE: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
      CACHEDIR: /cachedeps

    runs-on: ubuntu-latest
    name: Run tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache results by dependency diff
      uses: actions/cache@v2
      with:
        path: |
          ~/cachedeps
        key: ${{ github.sha }}-${{ github.ref }}

    - run: ls -lrt ~/cachedeps

    - run: >
        docker run --rm --entrypoint '' -v $PWD:/opt
        --env "QEMU_QMP_CONNECT_ATTEMPTS=10" --env "EXPECTED_QEMU_START_S=20"
        --env CACHEDIR
        -v $HOME/cachedeps:$CACHEDIR
        -v $PWD:/opt
        $IMAGE
        sh -c 'cd /opt && ./tools/install-patched-qemu.sh &&
        install-new-deps-dlp.sh && ./tools/cache-deps.sh'

    - run: ls -lrt ~/cachedeps
