name: Check dlp

on:
  push:
    branches: [action-check-dlp]

jobs:
  dlp:
    env:
      IMAGE: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
      CACHEDIR: /cachedeps

    runs-on: ubuntu-latest
    name: Run tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: env | sort

    - name: Cache results by dependency diff
      uses: actions/cache@v2
      with:
        path: |
          ~/cachedeps
        #key: ${{ github.sha }}-${{ github.ref }}
        key: ${{ github.ref }}

    - run: ls -lrt ~/cachedeps || true

    - run: >
        export JOBID=${{ github.job }}

        docker run --rm --entrypoint ''
        --env "QEMU_QMP_CONNECT_ATTEMPTS=10" --env "EXPECTED_QEMU_START_S=20"
        --env CACHEDIR
        --env JOBID
        -v $HOME/cachedeps:$CACHEDIR
        -v $PWD:/opt
        $IMAGE
        sh -c 'cd /opt && ./tools/install-patched-qemu.sh &&
        ./tools/install-new-deps-dlp.sh && ./tools/cache-deps.sh'

    - run: ls -l job-* || true
    - run: ls -lrt ~/cachedeps || true
